version: '3.8'

services:
  api:
    build: .
    user: "0:0"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - DATABASE_URL=${DATABASE_URL:-sqlite:///./data/app.db}
      - VNC_PASSWORD=${VNC_PASSWORD:-vncpassword}
      - WIDTH=1024
      - HEIGHT=768
      # optional: pass through if you set it in .env
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_DB=${MONGODB_DB:-computer_use}
    volumes:
      - ./data:/home/computeruse/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"
      - "6080:6080"
      - "5901:5900"

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - api
      - mongo   # ensure FE starts after API & Mongo (optional)

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=app
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  db-data:
  mongo-data: