name: lint-and-typecheck
on: [pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    defaults:
      run:
        working_directory: test
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v1
  pyright:
    runs-on: ubuntu-latest
    defaults:
      run:
        working_directory: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          cache: "pip"
      - run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r dev-requirements.txt
      - run: echo "$PWD/.venv/bin" >> $GITHUB_PATH
      - uses: jakebailey/pyright-action@v1
